@startuml UC_AccessControl
left to right direction
actor Customer as Buyer
actor Admin as SysAdmin

package "Access Control" {
  usecase "Register / Login" as UC_Login
  usecase "Logout" as UC_Logout
  usecase "Role Management" as UC_RoleMgmt
  usecase "Set Permissions" as UC_Perms
}

Buyer --> UC_Login
Buyer --> UC_Logout

SysAdmin --> UC_Login
SysAdmin --> UC_Logout
SysAdmin --> UC_RoleMgmt
SysAdmin --> UC_Perms
@enduml
