@startuml UC_ProductCatalog
left to right direction
skinparam packageStyle rectangle

actor Customer as Buyer
actor Admin as SysAdmin

package "Product Catalog" {
  usecase "Browse Menus" as UC_Browse
  usecase "Filter/Sort Items" as UC_FilterSort
  usecase "View Item Details" as UC_View
  usecase "Manage Menu (CRUD)" as UC_Manage
  usecase "Assign Item to Inventory" as UC_AssignInv
}

Buyer --> UC_Browse
Buyer --> UC_FilterSort
Buyer --> UC_View

SysAdmin --> UC_Manage
SysAdmin --> UC_AssignInv

UC_Manage .> UC_Browse : <<include>>
UC_View .> UC_Browse : <<include>>
@enduml
